|BUILD CONFIGURATION| [Linux] * Using ZED instead of re-writing a lot of what it already provides * Using the Git version information
[Pandora]
* Using ZED instead of re-writing a lot of what it already provides

|SOURCE|
* Removed all common files that are available in ZED
[Event]
* Using ZED data types
[EventListener]
* Using ZED data types
[EventRouter]
* Using ZED data types
[Events]
* Using ZED data types
[Game]
* Using ZED data types
* Added a ZED Window
[Hash]
* Using ZED data types
[InputEventListener]
* Using ZED data types
[Time]
* Using ZED data types
[WindowEventListener]
* Using ZED data types
[WindowEventRouter]
* Using ZED data types
* Temporarily commented-out the IEEE754 infinite constant, it is in another
  branch of ZED which this was not built against
[EventRouter]
* Using ZED data types
[Hash]
* Using ZED data types
[Linux::Game]
* Using ZED data types
* Commented-out the window creation and GLX context creation code
* Only a window is created, which is a non-decorated window that requires the
  user to place the pointer within the window's bounds to interact with it
[Linux::InputEventListener]
* Using ZED data types
[Linux::Main]
* Using ZED data types
[Linux::Time]
* Using ZED data types
[Linux::WindowEventListener]
* Using ZED data types

diff --git a/Source/Linux/Makefile b/Source/Linux/Makefile
--- a/Source/Linux/Makefile
+++ b/Source/Linux/Makefile
@@ -2,63 +2,121 @@
 #                                          Dawn Makefile [Linux x86] Ver. 1.0 #
 ###############################################################################
 
-TARGETDIR	= ../../Bin/$(PLATFORM)
-OBJSDIR		= ../../Obj/$(PLATFORM)/$(BUILD)
-SOURCEDIR	= Source
+ifeq ($(strip $(ZEDSDK)),)
+$(error Please set ZEDSDK to point to your ZED SDK root directory )
+endif
+
+ifndef TOPDIR
+export TOPDIR		:= $(shell cd ../../ && pwd)
+export TOPSRC		= $(TOPDIR)/Source
+export TARGETDIR	= $(TOPDIR)/Bin/$(PLATFORM)
+export OBJSDIR		= $(TOPDIR)/Obj/$(PLATFORM)/$(GCCVER)/$(BUILD)
+endif
+SOURCEDIR	= Source ../Common/Source
+#../Common/Source/OGLES2
 
 TARGET := Dawn
+OUTFILE	=	$(TARGETDIR)/$(TARGET)_$(GCCVER)
 
-# Get the machine type to determine which set of libraries to use
+PLATFORM		:= Linux
+BUILD_PLATFORM	:= LINUX
+BUILD_ARCH		:= X86
+ARCH			:= x86
+BITSIZE			:= 32
+
+GCCVER	= $(shell $(CPP) -dumpversion)
+
+BUILD_TYPE := debug
+
+32BIT ?= False
+64BIT ?= False
+
+##### Get the machine type to determine which set of libraries to use #########
 UNAME			= $(shell uname)
 UNAME_MACHINE	= $(shell uname -m)
 
-CC = g++
-
-CFLAGS_EXT =
 ifeq ($(UNAME), Linux)
-	CFLAGS_EXT	= -ffriend-injection -std=gnu++0x
+	CPPFLAGS_EXT	= -ffriend-injection -std=gnu++0x
 	SYSIPATH	= -I/usr/include/xorg
 	SYSLIBS		= -lX11 -lGL -lrt
+	LINKFLAGS	=
+##### Check for forced 32-bit or 64-bit builds ################################
+ifneq ($(64BIT), False)
+	CPPFLAGS_EXT	+=	-m64
+	ARCH		=	x86
+	BITSIZE		=	64
+else
+ifneq ($(32BIT), False)
+	CPPFLAGS_EXT	+=	-m32
+	ARCH		= x86
+	BITSIZE		= 32
+else
+##### Nothing forced.  Use what the machine reports ###########################
 ifeq ($(UNAME_MACHINE), x86_64)
-	BUILD_PLATFORM	= LINUX_X86_64
-	PLATFORM		= Linux_x86_64
+	CPPFLAGS_EXT	+=	-m64
+	ARCH		=	x86
+	BITSIZE		=	64
 endif
 ifeq ($(UNAME_MACHINE), i686)
-	BUILD_PLATFORM	= LINUX_X86_32
-	PLATFORM		= Linux_x86_32
+	CPPFLAGS_EXT	+=	-m32
+	ARCH		= x86
+	BITSIZE		= 32
+endif
+endif
 endif
 endif
 
+CPP = g++
+
+CPPFLAGS	=	-c -DZED_BUILD_$(BUILD_DEF) -DZED_PLATFORM_$(BUILD_PLATFORM) \
+				-DZED_PLATFORM_$(BUILD_PLATFORM)_$(BUILD_ARCH) \
+				-DZED_PLATFORM_$(BUILD_PLATFORM)_$(BUILD_ARCH)_$(BITSIZE) \
+				-DZED_BITSIZE_$(BITSIZE) -DZED_ARCH_$(BUILD_ARCH) \
+				-I$(TOPSRC)/Linux/Headers -I$(TOPSRC)/Common/Headers
+CPPFLAGS_EXT=	-ffriend-injection -std=c++0x
+SYSIPATH	=	-idirafter $(PNDSDK)/usr/include
+INCPATH		=	-I$(ZEDSDK)/include/Linux
+SYSLPATH	=	
+#-L$(PNDSDK)/usr/lib
+LIBPATH		=	-L$(ZEDSDK)/lib/Linux/$(ARCH)/$(BITSIZE)
+SYSLIBS		=	-lX11 -lGL -lXrandr -lrt -pthread
+LINKFLAGS	=
+
 ##### Debug #######
-debug:		BUILD = Debug
-debug:		BUILD_DEF = DEBUG
+debug:		BUILD		= Debug
+debug:		BUILD_TYPE	= debug
+debug:		BUILD_DEF	= DEBUG
 debug:		TARGET := $(TARGET)D
-debug:		CFLAGS = -c -g -ggdb -Wall -D_DEBUG $(CFLAGS_EXT)
+debug:		CPPFLAGS += -g -ggdb -Wall -D_DEBUG $(CPPFLAGS_EXT)
+debug:		LIBS = -lZEDRendererD -lZEDArithmeticD -lZEDSystemD
 debug:		$(TARGET)
 
 ##### Release #####
-release:	BUILD = Release
-release:	BUILD_DEF = RELEASE
+release:	BUILD		= Release
+release:	BUILD_TYPE	= release
+release:	BUILD_DEF	= RELEASE
 release:	TARGET := $(TARGET)
-release:	CFLAGS = -c -O3 $(CFLAGS_EXT)
+release:	CPPFLAGS += -O3 $(CPPFLAGS_EXT)
+release:	LINKFLAGS += -Wl,-S
 release:	$(TARGET)
 
 ##### Profile #####
-profile:	BUILD = Profile
-profile:	BUILD_DEF = PROFILE
+profile:	BUILD		= Profile
+profile:	BUILD_TYPE	= profile
+profile:	BUILD_DEF	= PROFILE
 profile:	TARGET := $(TARGET)P
-profile:	CFLAGS = -c -O3 -g -ggdb -Wall -D_DEBUG $(CFLAGS_EXT)
+profile:	CPPFLAGS += -O3 -g -ggdb -Wall -D_DEBUG $(CPPFLAGS_EXT)
 profile:	$(TARGET)
 
 ##### Build the object files while not in the Obj directory ###################
-ifneq ($(OBJSDIR), $(notdir $(CURDIR)))
-
-.PHONY: VERSIONINFO OBJSDIR TARGETDIR
+ifneq ($(OBJSDIR), $(CURDIR))
 
 VERSIONINFO:
-	@echo "---------------------- Generating Version Information -------------------------"
-	@sh ./HgVersion.sh
-	@echo "-------------------------------------------------------------------------------"
+	@printf "%s" "------------------------- Generating Version Information ---"
+	@printf "%s\n" "-------------------"
+	@sh ./GitVersion.sh ./Headers/GitVersion.hpp
+	@printf "%s" "------------------------------------------------------------"
+	@printf "%s\n" "-------------------"
 
 TARGETDIR:
 	@mkdir -p $(TARGETDIR)
@@ -67,28 +125,71 @@ OBJSDIR:
 	@mkdir -p $(OBJSDIR)
 
 CPPFILES	:= $(foreach dir,$(SOURCEDIR),$(notdir $(wildcard $(dir)/*.cpp)))
-COMFILES	:= $(foreach dir,../Common/Source,$(notdir $(wildcard $(dir)/*.cpp)))
+export VPATH	:= $(foreach dir,$(SOURCEDIR),$(CURDIR)/$(dir))
+export OBJS		:= $(CPPFILES:.cpp=.o)
 
+$(TARGET): OBJSDIR TARGETDIR VERSIONINFO
+	@/usr/bin/time -f "%E" -o $(OBJSDIR)/compiletime $(MAKE) \
+	--no-print-directory -C $(OBJSDIR) -f $(TOPSRC)/Linux/Makefile \
+	$(BUILD_TYPE)
+	@printf "\n%s" "----------------------------------------------------------"
+	@printf "%s\n" "---------------------"
+	@printf "Compile time: "
+	@cat $(OBJSDIR)/compiletime
+	@printf "%s" "------------------------------------------------------------"
+	@printf "%s\n" "-------------------"
 
-###############
-OBJS	= $(CPPFILES:.cpp=.o)
-COBJS	= $(COMFILES:.cpp=.o)
-HEADERS	= $(wildcard *.hpp)
-###############
+else
 
-$(TARGET): VERSIONINFO OBJSDIR TARGETDIR $(OBJS) $(COBJS)
-	cd $(OBJSDIR) && $(CC) -o ../$(TARGETDIR)/$(TARGET) $(OBJS) $(COBJS) $(SYSLIBS)
+##### In the intermediate build directory #####################################
 
-%.o: ../Common/Source/%.cpp
-	$(CC) $(CFLAGS) -DBUILD_$(BUILD_DEF) -DPLATFORM_$(BUILD_PLATFORM) -IHeaders -I../Common/Headers $(SYSIPATH) $< -o $(OBJSDIR)/$@
+$(TARGET): $(OBJS)
+	@printf "\n\n%s" "------------------------- MESSAGES FROM THE COMPILER ---"
+	@printf "%s\n" "-----------------------"
+	@cat *.cmsgs
+	@printf "%s" "------------------------------------------------------------"
+	@printf "%s\n\n" "-------------------"
+	@printf "Creating: $(OUTFILE)... "
+	@$(CPP) -o $(OUTFILE) $(LINKFLAGS) $(OBJS) $(SYSLPATH) $(LIBPATH) \
+	$(SYSLIBS) $(LIBS) 2> lmsgs;\
+	RETVAL=$$?;\
+	if [[ $$RETVAL == 0 ]]; then\
+		printf "[OK]\n";\
+	else\
+		printf "\n\n%s" "------------------------------------ ERROR --------";\
+		printf "%s\n" "----------------------------";\
+		cat lmsgs;\
+		printf "%s" "-------------------------------------------------------";\
+		printf "%s\n" "------------------------";\
+		exit 1;\
+	fi
 
-%.o: $(SOURCEDIR)/%.cpp 
-	$(CC) $(CFLAGS) -DBUILD_$(BUILD_DEF) -DPLATFORM_$(BUILD_PLATFORM) -IHeaders -I../Common/Headers $(SYSIPATH) $< -o $(OBJSDIR)/$@
+%.o: %.cpp
+	@printf "Compiling: $<... "
+	@$(CPP) -MMD -MP -MF $*.d $(CPPFLAGS) $(SYSIPATH) $(INCPATH) \
+	$< -o $@ 2> $*.cmsgs;\
+	RETVAL=$$?;\
+	if [[ $$RETVAL == 0 ]]; then\
+		printf "[OK]\n";\
+	else\
+		printf "\n\n%s" "--------------------------------- ERROR -----------";\
+		printf "%s\n" "----------------------------";\
+		cat $*.cmsgs;\
+		printf "%s" "-------------------------------------------------------";\
+		printf "%s\n\n" "------------------------";\
+		exit 1;\
+	fi
+
+-include $(OBJSDIR)/*.d
 
 endif
 
 .PHONY: clean
 clean:
-	cd $(TARGETDIR) && rm -f ./*
-	cd $(OBJSDIR) && rm -rf ./*
+	@printf "Removing files from: $(TARGETDIR)... "
+	@cd $(TARGETDIR) && rm -f ./*
+	@printf "[OK]\n"
+	@printf "Removing files from: $(OBJSDIR)... "
+	@cd $(OBJSDIR) && rm -rf ./*
+	@printf "[OK]\n"
 
diff --git a/Source/Pandora/Makefile b/Source/Pandora/Makefile
--- a/Source/Pandora/Makefile
+++ b/Source/Pandora/Makefile
@@ -7,6 +7,10 @@ ifeq ($(strip $(PNDSDK)),)
 $(error Please set PNDSDK to point to your Pandora toolchain root directory  )
 endif
 
+ifeq ($(strip $(ZEDSDK)),)
+$(error Please set ZEDSDK to point to your ZED SDK root directory )
+endif
+
 ifndef TOPDIR
 export TOPDIR		:= $(shell cd ../../ && pwd)
 export TOPSRC		= $(TOPDIR)/Source
@@ -40,7 +44,9 @@ CPPFLAGS_EXT=	-ffriend-injection -std=c++0x -mcpu=cortex-a8 \
 				-Wa,-mcpu=cortex-a8 -mfpu=neon -Wa,-mfpu=neon \
 				-mfloat-abi=softfp
 SYSIPATH	=	-idirafter $(PNDSDK)/usr/include
+INCPATH		=	-I$(ZEDSDK)/include/Pandora
 SYSLPATH	=	-L$(PNDSDK)/usr/lib
+LIBPATH		=	-L$(ZEDSDK)/lib/Pandora
 SYSLIBS		=	-lX11 -lGLESv2 -lEGL -lrt -lc -lIMGegl -lXau -lXdmcp -lsrv_um
 LINKFLAGS	=
 
@@ -50,6 +56,7 @@ debug:		BUILD_TYPE	= debug
 debug:		BUILD_DEF	= DEBUG
 debug:		TARGET := $(TARGET)D
 debug:		CPPFLAGS += -g -ggdb -Wall -D_DEBUG $(CPPFLAGS_EXT)
+debug:		LIBS = -lZEDRendererD -lZEDArithmeticD -lZEDSystemD
 debug:		$(TARGET)
 
 ##### Release #####
@@ -111,12 +118,24 @@ $(TARGET): $(OBJS)
 	@printf "%s" "------------------------------------------------------------"
 	@printf "%s\n\n" "-------------------"
 	@printf "Creating: $(OUTFILE)... "
-	@$(CPP) -o $(OUTFILE) $(LINKFLAGS) $(OBJS) $(SYSLPATH) $(SYSLIBS) 2> lmsgs
-	@printf "[OK]\n"
+	@$(CPP) -o $(OUTFILE) $(LINKFLAGS) $(OBJS) $(SYSLPATH) $(LIBPATH) \
+	$(SYSLIBS) $(LIBS) 2> lmsgs;\
+	RETVAL=$$?;\
+	if [[ $$RETVAL == 0 ]]; then\
+		printf "[OK]\n";\
+	else\
+		printf "\n\n%s" "------------------------------------ ERROR --------";\
+		printf "%s\n" "----------------------------";\
+		cat lmsgs;\
+		printf "%s" "-------------------------------------------------------";\
+		printf "%s\n" "------------------------";\
+		exit 1;\
+	fi
 
 %.o: %.cpp
 	@printf "Compiling: $<... "
-	@$(CPP) -MMD -MP -MF $*.d $(CPPFLAGS) $(SYSIPATH) $< -o $@ 2> $*.cmsgs;\
+	@$(CPP) -MMD -MP -MF $*.d $(CPPFLAGS) $(SYSIPATH) $(INCPATH) \
+	$< -o $@ 2> $*.cmsgs;\
 	RETVAL=$$?;\
 	if [[ $$RETVAL == 0 ]]; then\
 		printf "[OK]\n";\
